apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      name: frontend
  replicas: 1
  template:
    metadata:
      labels:
        name: frontend
    spec:
      imagePullSecrets: 
      - name: docker
      containers:
      - name: nginx
        image: docker.dataenv.de/root_frontend:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    name: frontend
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http